// イベントtype変数
export const LOGIN_LOGIN_ON_CLICK = 'LOGIN_LOGIN_ON_CLICK';

export const GAMEN1_ENTER_TEXT = 'GAMEN1_ENTER_TEXT';
export const GAMEN1_REGIST_ON_CLICK = 'GAMEN1_REGIST_ON_CLICK';

export const GAMEN2_SELECT_ON_CHANGE = 'GAMEN2_SELECT_ON_CHANGE';
export const GAMEN2_SEARCH_ON_CLICK = 'GAMEN2_SEARCH_ON_CLICK';

export const GAMEN4_DROPDOWN1_ON_CHANGE = 'GAMEN4_DROPDOWN1_ON_CHANGE';
export const GAMEN4_DROPDOWN2_ON_CHANGE = 'GAMEN4_DROPDOWN2_ON_CHANGE';
export const GAMEN4_DROPDOWN3_ON_CHANGE = 'GAMEN4_DROPDOWN3_ON_CHANGE';
export const GAMEN4_DROPDOWN4_ON_CHANGE = 'GAMEN4_DROPDOWN4_ON_CHANGE';
export const GAMEN4_CUSTOMER_KEITAI_RADIOS_ON_CLICK = 'GAMEN4_CUSTOMER_KEITAI_RADIOS_ON_CLICK';
export const GAMEN4_DIALOG1_OPEN = 'GAMEN4_DIALOG1_OPEN';
export const GAMEN4_DIALOG1_CLOSE = 'GAMEN4_DIALOG1_CLOSE';
